"""order-book-engine — Deterministic limit order book matching and execution analytics"""

__version__ = "0.1.0"

from .event_replay import (
    ACCEPTED,
    CONFIG_MISMATCH,
    DUPLICATE,
    DUPLICATE_EXECUTION_PLAN,
    EVENT_ID_CONFLICT,
    EXECUTION_PLAN_CLOSED,
    EventReplayer,
    FORMAT_VERSION,
    INVALID_EVENT,
    OUT_OF_ORDER,
    PLAN_ACTIVE,
    PLAN_CANCELLED,
    PLAN_COMPLETED,
    PRICE_LIMIT_EXCEEDED,
    REJECTED,
    SEQUENCE_GAP,
    SNAPSHOT_CORRUPT,
    SNAPSHOT_VERSION_UNSUPPORTED,
    SnapshotError,
    TWAP_CANCEL,
    TWAP_REPORT,
    TWAP_SLICE,
    TWAP_START,
    UNKNOWN_EXECUTION_PLAN,
    VWAP_CANCEL,
    VWAP_REPORT,
    VWAP_SLICE,
    VWAP_START,
    canonical_json,
    export_snapshot,
    replay_events,
    restore_replayer,
)

__all__ = [
    "ACCEPTED",
    "CONFIG_MISMATCH",
    "DUPLICATE",
    "DUPLICATE_EXECUTION_PLAN",
    "EVENT_ID_CONFLICT",
    "EXECUTION_PLAN_CLOSED",
    "EventReplayer",
    "FORMAT_VERSION",
    "INVALID_EVENT",
    "OUT_OF_ORDER",
    "PLAN_ACTIVE",
    "PLAN_CANCELLED",
    "PLAN_COMPLETED",
    "PRICE_LIMIT_EXCEEDED",
    "REJECTED",
    "SEQUENCE_GAP",
    "SNAPSHOT_CORRUPT",
    "SNAPSHOT_VERSION_UNSUPPORTED",
    "SnapshotError",
    "TWAP_CANCEL",
    "TWAP_REPORT",
    "TWAP_SLICE",
    "TWAP_START",
    "UNKNOWN_EXECUTION_PLAN",
    "VWAP_CANCEL",
    "VWAP_REPORT",
    "VWAP_SLICE",
    "VWAP_START",
    "canonical_json",
    "export_snapshot",
    "replay_events",
    "restore_replayer",
]
